server:
  port: 8084

spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:mysql://mysql-container:3306/paymentdb
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  cloud:
    config:
      enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
      #defaultZone: http://localhost:8761/eureka/

