server:
  port: 8082
spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:mysql://mysql-container:3306/orderdb
    #url: jdbc:mysql://localhost:3306/orderdb        #local mysql
    username: root
    password: root
   #password: password123   #local mysql password
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  cloud:
    config:
      enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console

#  cloud:
#    config:
#      enabled: false

# as we have commented eureka client details and we are taking it from config-server, we have to tell it to this service
#  config:
#    import: configserver:http://localhost:9296


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
#      defaultZone: http://localhost:8761/eureka/


