server:
  port: 8082
spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:mysql://mysql-container:3306/orderdb
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  cloud:
    config:
      enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
#spring:
#  application:
#    name: ORDER-SERVICE
#  cloud:
#    config:
#      enabled: false
#  datasource:
##    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb   #this is for local machine db
#    url: jdbc:mysql://mysql-container:3306/orderdb   #this is for docker machine db
#    username: root
#    password: root   #docker mysql password
#    #password: password123   #local mysql password
#  jpa:
#    show-sql: true
#    generate-ddl: true
#    properties:
#      hibernate:
#        ddl-auto: update
#        dialect: org.hibernate.dialect.MySQL8Dialect

  # as we have commented eureka client details and we are taking it from config-server, we have to tell it to this service
#  config:
#    import: configserver:http://localhost:9296


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
#      defaultZone: http://localhost:8761/eureka/


