package com.elite.springboot.productservice.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data //getter setter are inbuilt generated by lombok [Getter, Setter, RequiredArgsConstructor, ToString, EqualsAndHashCode, Value]

@AllArgsConstructor //constructor with all arguments will be generated
@NoArgsConstructor
@Builder //give builder pattern implementation
public class Product {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)  //primary key, will be increased by 1 each time
    private long productId;

    @Column(name = "PRODUCT_NAME") //column name will be shown as this in db
    private String productName;

    @Column(name="PRICE")
    private long price;

    @Column(name="QUANTITY")
    private long quantity;
}
